name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir csv-converter \
            && cp *.php csv-converter \
            && cp -r projects csv-converter \
            && cp -r utils csv-converter \
            && tar -zcf csv-converter.tar.gz csv-converter
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: csv-converter.tar.gz

